version: '3.8'

services:
  # PostgreSQL 数据库服务
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tools_aigc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 应用服务
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/tools_aigc
      - DATABASE_POOL_SIZE=5
      - DATABASE_MAX_OVERFLOW=10
    command: >
      sh -c "
        echo '等待数据库完全启动...' &&
        sleep 2 &&
        echo '运行数据库迁移...' &&
        alembic upgrade head &&
        echo '启动应用...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data:
