"""初始化数据库结构

Revision ID: a6ed2d419cc7
Revises: 
Create Date: 2025-03-24 11:53:47.469318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6ed2d419cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apilog',
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP方法'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='请求路径'),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='查询参数'),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求头'),
    sa.Column('client_ip', sa.String(length=50), nullable=True, comment='客户端IP'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='用户代理'),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='请求体'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='状态码'),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='响应体'),
    sa.Column('process_time', sa.Integer(), nullable=True, comment='处理时间（毫秒）'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='用户ID'),
    sa.Column('error', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='全名'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'API', name='userrole'), nullable=False, comment='用户角色'),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), nullable=False, comment='权限列表'),
    sa.Column('api_key', sa.String(length=255), nullable=True, comment='API密钥'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='自定义额外数据'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_api_key'), 'user', ['api_key'], unique=True, schema='public')
    op.create_index(op.f('ix_public_user_email'), 'user', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_user_username'), 'user', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_username'), table_name='user', schema='public')
    op.drop_index(op.f('ix_public_user_email'), table_name='user', schema='public')
    op.drop_index(op.f('ix_public_user_api_key'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    op.drop_table('apilog', schema='public')
    # ### end Alembic commands ###